name: ttrt
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_fonts: ^3.0.1
  package_info_plus: ^1.4.2
  stop_watch_timer: ^1.5.0
  url_launcher: ^6.1.2

dev_dependencies:
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
